# Tests for ChunkFormatter (TDD - write tests first)

"""Tests for chunk formatting functionality.

These tests verify the chunk formatting for embeddings:
- Header includes channel, time range, participants with nicknames
- Reply indicators show "(reply to X)"
- Messages with no content show [no text]
- Unique chunk IDs are generated
- Formatted text preserves conversation structure
"""

from __future__ import annotations

import datetime
import uuid

from strofkabot.db.message_history import HistoryMessage
from strofkabot.rag.chunking.chunk_formatter import ChunkFormatter, FormattedChunk
from strofkabot.rag.chunking.conversation_grouper import ConversationGroup


class TestFormattedChunk:
    """Tests for FormattedChunk dataclass."""

    def test_creation(self, sample_messages):
        """FormattedChunk should be creatable with required fields."""
        chunk = FormattedChunk(
            chunk_id="test-chunk-id",
            raw_text="Some raw text",
            formatted_text="[Header]\nSome raw text",
            messages=sample_messages[:2],
            metadata={"channel_id": 100},
        )

        assert chunk.chunk_id == "test-chunk-id"
        assert "Some raw text" in chunk.raw_text
        assert chunk.metadata["channel_id"] == 100

    def test_chunk_id_is_valid_uuid(self):
        """Chunk IDs generated by formatter should be valid UUIDs."""
        # This will be tested via the formatter
        chunk = FormattedChunk(
            chunk_id=str(uuid.uuid4()),
            raw_text="",
            formatted_text="",
            messages=[],
            metadata={},
        )

        # Should not raise
        uuid.UUID(chunk.chunk_id)


class TestChunkFormatterBasics:
    """Basic tests for ChunkFormatter."""

    def test_creation_without_nicknames(self):
        """ChunkFormatter should work without nickname mappings."""
        formatter = ChunkFormatter(nicknames=None)
        assert formatter is not None

    def test_creation_with_nicknames(self, sample_nicknames):
        """ChunkFormatter should accept nickname mappings."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)
        assert formatter is not None


class TestFormatHeader:
    """Tests for header formatting."""

    def test_header_includes_channel_name(self, sample_messages, sample_nicknames):
        """Header should include channel name."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=sample_messages[0].timestamp,
            end_time=sample_messages[2].timestamp,
            messages=sample_messages[:3],
            participant_ids={sample_messages[0].author_id, sample_messages[1].author_id},
        )

        chunk = formatter.format_for_embedding(group)

        assert "kanapeja" in chunk.formatted_text

    def test_header_includes_date_range(self, sample_messages, sample_nicknames):
        """Header should include date range."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=sample_messages[0].timestamp,
            end_time=sample_messages[2].timestamp,
            messages=sample_messages[:3],
            participant_ids={sample_messages[0].author_id, sample_messages[1].author_id},
        )

        chunk = formatter.format_for_embedding(group)

        # Should contain date in some form
        assert "2025-10-15" in chunk.formatted_text or "15" in chunk.formatted_text

    def test_header_includes_participant_names(self, sample_messages, sample_nicknames):
        """Header should list participant names."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=sample_messages[0].timestamp,
            end_time=sample_messages[2].timestamp,
            messages=sample_messages[:3],
            participant_ids={sample_messages[0].author_id, sample_messages[1].author_id},
        )

        chunk = formatter.format_for_embedding(group)

        # Should contain author names
        assert "Takarak" in chunk.formatted_text
        assert "basstein" in chunk.formatted_text

    def test_header_includes_nicknames(self, sample_messages, sample_nicknames):
        """Header should include nicknames after display names."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=sample_messages[0].timestamp,
            end_time=sample_messages[2].timestamp,
            messages=sample_messages[:3],
            participant_ids={sample_messages[0].author_id, sample_messages[1].author_id},
        )

        chunk = formatter.format_for_embedding(group)

        # Nicknames for Takarak (taka) and basstein (bas, bass, basi)
        assert "taka" in chunk.formatted_text
        assert "bas" in chunk.formatted_text


class TestFormatMessages:
    """Tests for message formatting within chunks."""

    def test_messages_have_author_prefix(self, sample_messages, sample_nicknames):
        """Each message should start with author name."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=sample_messages[0].timestamp,
            end_time=sample_messages[0].timestamp,
            messages=[sample_messages[0]],
            participant_ids={sample_messages[0].author_id},
        )

        chunk = formatter.format_for_embedding(group)

        # Message should have author prefix
        assert "Takarak:" in chunk.formatted_text or "Takarak (" in chunk.formatted_text

    def test_reply_indicator_included(self, sample_messages, sample_nicknames):
        """Reply messages should show reply indicator."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        # Messages 4-5 are a reply chain
        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=sample_messages[4].timestamp,
            end_time=sample_messages[4].timestamp,
            messages=[sample_messages[4]],  # This is a reply
            participant_ids={sample_messages[4].author_id},
        )

        chunk = formatter.format_for_embedding(group)

        # Should indicate it's a reply
        assert "reply" in chunk.formatted_text.lower() or "→" in chunk.formatted_text

    def test_empty_content_shows_placeholder(self, sample_nicknames):
        """Messages with empty content should show [no text]."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        base_time = datetime.datetime(2025, 10, 15, 14, 0, 0, tzinfo=datetime.UTC)
        empty_msg = HistoryMessage(
            id=1,
            channel_id=100,
            channel_name="kanapeja",
            author_id=301411562487545857,
            author_name="Takarak",
            content="",
            timestamp=base_time,
            reply_to_id=None,
            reply_to_author=None,
            reply_to_content=None,
            reactions="[]",
        )

        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=base_time,
            end_time=base_time,
            messages=[empty_msg],
            participant_ids={301411562487545857},
        )

        chunk = formatter.format_for_embedding(group)

        # Should show placeholder for empty content
        assert "[no text]" in chunk.formatted_text or "[empty]" in chunk.formatted_text


class TestRawText:
    """Tests for raw text extraction."""

    def test_raw_text_contains_message_content(self, sample_messages, sample_nicknames):
        """Raw text should contain the actual message content."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=sample_messages[0].timestamp,
            end_time=sample_messages[0].timestamp,
            messages=[sample_messages[0]],
            participant_ids={sample_messages[0].author_id},
        )

        chunk = formatter.format_for_embedding(group)

        # Raw text should have the message content
        assert "Hey everyone" in chunk.raw_text

    def test_raw_text_combines_multiple_messages(self, sample_messages, sample_nicknames):
        """Raw text should combine all messages."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=sample_messages[0].timestamp,
            end_time=sample_messages[2].timestamp,
            messages=sample_messages[:3],
            participant_ids={sample_messages[0].author_id, sample_messages[1].author_id},
        )

        chunk = formatter.format_for_embedding(group)

        # All message contents should be in raw text
        assert "Hey everyone" in chunk.raw_text
        assert "Not much" in chunk.raw_text
        assert "Same here" in chunk.raw_text


class TestMetadata:
    """Tests for metadata generation."""

    def test_metadata_includes_channel_info(self, sample_messages, sample_nicknames):
        """Metadata should include channel_id and channel_name."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=sample_messages[0].timestamp,
            end_time=sample_messages[0].timestamp,
            messages=[sample_messages[0]],
            participant_ids={sample_messages[0].author_id},
        )

        chunk = formatter.format_for_embedding(group)

        assert chunk.metadata["channel_id"] == 100
        assert chunk.metadata["channel_name"] == "kanapeja"

    def test_metadata_includes_time_info(self, sample_messages, sample_nicknames):
        """Metadata should include temporal information."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=sample_messages[0].timestamp,
            end_time=sample_messages[2].timestamp,
            messages=sample_messages[:3],
            participant_ids={sample_messages[0].author_id},
        )

        chunk = formatter.format_for_embedding(group)

        assert "start_time" in chunk.metadata
        assert "end_time" in chunk.metadata
        assert chunk.metadata["year"] == 2025
        assert chunk.metadata["month"] == 10

    def test_metadata_includes_participant_ids(self, sample_messages, sample_nicknames):
        """Metadata should include participant IDs."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=sample_messages[0].timestamp,
            end_time=sample_messages[2].timestamp,
            messages=sample_messages[:3],
            participant_ids={sample_messages[0].author_id, sample_messages[1].author_id},
        )

        chunk = formatter.format_for_embedding(group)

        # Participant IDs should be comma-separated string
        assert "participant_ids" in chunk.metadata
        assert str(sample_messages[0].author_id) in chunk.metadata["participant_ids"]

    def test_metadata_includes_message_count(self, sample_messages, sample_nicknames):
        """Metadata should include message count."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=sample_messages[0].timestamp,
            end_time=sample_messages[2].timestamp,
            messages=sample_messages[:3],
            participant_ids={sample_messages[0].author_id},
        )

        chunk = formatter.format_for_embedding(group)

        assert chunk.metadata["message_count"] == 3

    def test_metadata_includes_reply_chain_flag(self, sample_messages, sample_nicknames):
        """Metadata should indicate if chunk is a reply chain."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        # Reply chain messages (4, 5, 6)
        reply_messages = sample_messages[3:6]
        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=reply_messages[0].timestamp,
            end_time=reply_messages[-1].timestamp,
            messages=reply_messages,
            participant_ids={m.author_id for m in reply_messages},
        )

        chunk = formatter.format_for_embedding(group)

        assert chunk.metadata["is_reply_chain"] is True


class TestChunkIdGeneration:
    """Tests for unique chunk ID generation."""

    def test_chunk_id_is_unique(self, sample_messages, sample_nicknames):
        """Each call should generate a unique chunk ID."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=sample_messages[0].timestamp,
            end_time=sample_messages[0].timestamp,
            messages=[sample_messages[0]],
            participant_ids={sample_messages[0].author_id},
        )

        chunk1 = formatter.format_for_embedding(group)
        chunk2 = formatter.format_for_embedding(group)

        assert chunk1.chunk_id != chunk2.chunk_id

    def test_chunk_id_is_valid_uuid_format(self, sample_messages, sample_nicknames):
        """Chunk ID should be valid UUID format."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=sample_messages[0].timestamp,
            end_time=sample_messages[0].timestamp,
            messages=[sample_messages[0]],
            participant_ids={sample_messages[0].author_id},
        )

        chunk = formatter.format_for_embedding(group)

        # Should not raise
        uuid.UUID(chunk.chunk_id)


class TestCharacterCount:
    """Tests for character count in metadata."""

    def test_total_chars_calculated(self, sample_messages, sample_nicknames):
        """Metadata should include total character count."""
        formatter = ChunkFormatter(nicknames=sample_nicknames)

        group = ConversationGroup(
            channel_id=100,
            channel_name="kanapeja",
            start_time=sample_messages[0].timestamp,
            end_time=sample_messages[2].timestamp,
            messages=sample_messages[:3],
            participant_ids={sample_messages[0].author_id},
        )

        chunk = formatter.format_for_embedding(group)

        # total_chars should be sum of message content lengths
        expected_chars = sum(len(m.content) for m in sample_messages[:3])
        assert chunk.metadata["total_chars"] == expected_chars
